# Generated by Django 5.1.7 on 2025-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='car_photos/')),
            ],
        ),
    ]
